version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nicu_op_db_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"