package com.example.nicu.dto.documents

import kotlinx.serialization.Serializable

@Serializable
data class DynamicObservationSheetDto(
    val diaryDateTime: String? = null,
    val diaryState: String? = null,
    val diaryDynamicSate: String? = null,
    val diaryBreath: String? = null,
    val diaryTemperature: String? = null,
    val diaryHeartRate: String? = null,
    val diaryBreathRate: String? = null,
    val diarySkin: String? = null,
    val diarySkinRashes: String? = null,
    val diarySkinExtra: String? = null,
    val diarySkinExtraType: List<String>? = null,
    val diaryBioBreath: String? = null,
    val diaryWheezing: String? = null,
    val diaryWheezingExtra: String? = null,
    val diaryHeartTone: String? = null,
    val diaryHeartToneExtra: String? = null,
    val diaryStomach: List<String>? = null,
    val diaryFeeding: String? = null,
    val diaryFeedingCount: String? = null,
    val diaryFeedingType: List<String>? = null,
    val diaryFeedingTypeMix: String? = null,
    val diaryFeedingTypeExtra: String? = null,
    val diaryFeedingProbe: String? = null,
    val diaryUrinated: String? = null,
    val diaryUrinatedExtra: String? = null,
    val diaryDefecation: String? = null,
    val diaryDefecationExtra: String? = null,
    val diaryExtraData: String? = null,
    val diaryAppointed: String? = null,

    val diaryDateTime2: String? = null,
    val diaryState2: String? = null,
    val diaryDynamicSate2: String? = null,
    val diaryBreath2: String? = null,
    val diaryTemperature2: String? = null,
    val diaryHeartRate2: String? = null,
    val diaryBreathRate2: String? = null,
    val diarySkin2: String? = null,
    val diarySkinRashes2: String? = null,
    val diarySkinExtra2: String? = null,
    val diarySkinExtraType2: List<String>? = null,
    val diaryBioBreath2: String? = null,
    val diaryWheezing2: String? = null,
    val diaryWheezingExtra2: String? = null,
    val diaryHeartTone2: String? = null,
    val diaryHeartToneExtra2: String? = null,
    val diaryStomach2: List<String>? = null,
    val diaryFeeding2: String? = null,
    val diaryFeedingCount2: String? = null,
    val diaryFeedingType2: List<String>? = null,
    val diaryFeedingTypeMix2: String? = null,
    val diaryFeedingTypeExtra2: String? = null,
    val diaryFeedingProbe2: String? = null,
    val diaryUrinated2: String? = null,
    val diaryUrinatedExtra2: String? = null,
    val diaryDefecation2: String? = null,
    val diaryDefecationExtra2: String? = null,
    val diaryExtraData2: String? = null,
    val diaryAppointed2: String? = null,

    val diaryDateTime3: String? = null,
    val diaryState3: String? = null,
    val diaryDynamicSate3: String? = null,
    val diaryBreath3: String? = null,
    val diaryTemperature3: String? = null,
    val diaryHeartRate3: String? = null,
    val diaryBreathRate3: String? = null,
    val diarySkin3: String? = null,
    val diarySkinRashes3: String? = null,
    val diarySkinExtra3: String? = null,
    val diarySkinExtraType3: List<String>? = null,
    val diaryBioBreath3: String? = null,
    val diaryWheezing3: String? = null,
    val diaryWheezingExtra3: String? = null,
    val diaryHeartTone3: String? = null,
    val diaryHeartToneExtra3: String? = null,
    val diaryStomach3: List<String>? = null,
    val diaryFeeding3: String? = null,
    val diaryFeedingCount3: String? = null,
    val diaryFeedingType3: List<String>? = null,
    val diaryFeedingTypeMix3: String? = null,
    val diaryFeedingTypeExtra3: String? = null,
    val diaryFeedingProbe3: String? = null,
    val diaryUrinated3: String? = null,
    val diaryUrinatedExtra3: String? = null,
    val diaryDefecation3: String? = null,
    val diaryDefecationExtra3: String? = null,
    val diaryExtraData3: String? = null,
    val diaryAppointed3: String? = null,
) : DocumentDto